In [17]:
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
import os 
print(os.getcwd())

C:\Users\princ\Downloads\project


In [19]:
df = pd.read_csv('churn.all')

In [20]:
df.head(5)

state  account_length  area_code phone_number intl_plan voice_mail_plan  \
0    KS             128        415     382-4657        no             yes   
1    OH             107        415     371-7191        no             yes   
2    NJ             137        415     358-1921        no              no   
3    OH              84        408     375-9999       yes              no   
4    OK              75        415     330-6626       yes              no   

   number_vmail_messages  total_day_minutes  total_day_calls  \
0                     25              265.1              110   
1                     26              161.6              123   
2                      0              243.4              114   
3                      0              299.4               71   
4                      0              166.7              113   

   total_day_charge  total_eve_minutes  total_eve_calls  total_eve_charge  \
0             45.07              197.4               99             16.78   
1             27.47              195.5              103             16.62   
2             41.38              121.2              110             10.30   
3             50.90               61.9               88              5.26   
4             28.34              148.3              122             12.61   

   total_night_minutes  total_night_calls  total_night_charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   total_intl_minutes  total_intl_calls  total_intl_charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   number_customer_service_calls  churned  
0                              1   False.  
1                              1   False.  
2                              0   False.  
3                              2   False.  
4                              3   False.

In [21]:
# Define a function to visulize the features with missing values, and % of total values, & datatype
def missing_values_table(df):
     # Total missing values
    mis_val = df.isnull().sum()
    # Percentage of missing values
    mis_val_percent = 100 * df.isnull().sum() / len(df)
    mis_val_type = df.dtypes
    # Make a table with the results
    mis_val_table = pd.concat([mis_val, mis_val_percent, mis_val_type], axis=1)
        
     # Rename the columns
    mis_val_table_ren_columns = mis_val_table.rename(columns = {0 : 'Missing Values', 1 : '% of Total Values', 2: 'type'})
        
    # Sort the table by percentage of missing descending
    mis_val_table_ren_columns = mis_val_table_ren_columns[ mis_val_table_ren_columns.iloc[:,1] != 0].sort_values('% of Total Values', ascending=False).round(1)
        
    # Print some summary information
    print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n" "There are " + str(mis_val_table_ren_columns.shape[0]) + " columns that have missing values.")
        
    # Return the dataframe with missing information
    return mis_val_table_ren_columns

In [22]:
missing_values_table(df)

Your selected dataframe has 21 columns.
There are 0 columns that have missing values.


Empty DataFrame
Columns: [Missing Values, % of Total Values, type]
Index: []

In [23]:
df.head(5)

state  account_length  area_code phone_number intl_plan voice_mail_plan  \
0    KS             128        415     382-4657        no             yes   
1    OH             107        415     371-7191        no             yes   
2    NJ             137        415     358-1921        no              no   
3    OH              84        408     375-9999       yes              no   
4    OK              75        415     330-6626       yes              no   

   number_vmail_messages  total_day_minutes  total_day_calls  \
0                     25              265.1              110   
1                     26              161.6              123   
2                      0              243.4              114   
3                      0              299.4               71   
4                      0              166.7              113   

   total_day_charge  total_eve_minutes  total_eve_calls  total_eve_charge  \
0             45.07              197.4               99             16.78   
1             27.47              195.5              103             16.62   
2             41.38              121.2              110             10.30   
3             50.90               61.9               88              5.26   
4             28.34              148.3              122             12.61   

   total_night_minutes  total_night_calls  total_night_charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   total_intl_minutes  total_intl_calls  total_intl_charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   number_customer_service_calls  churned  
0                              1   False.  
1                              1   False.  
2                              0   False.  
3                              2   False.  
4                              3   False.

In [24]:
df['voice_mail_plan'][0]

' yes'

In [25]:
df['voice_mail_plan'] = df['voice_mail_plan'].map(lambda x: x.strip())
df['intl_plan'] = df['intl_plan'].map(lambda x: x.strip())
df['churned'] = df['churned'].map(lambda x: x.strip())

In [26]:
df['voice_mail_plan'][0]

'yes'

In [27]:
# yes/no -> 0/1
df['voice_mail_plan'] = df['voice_mail_plan'].map({'no':0, 'yes':1})
df.intl_plan = df.intl_plan.map({'no':0, 'yes':1})

In [28]:
df.churned.value_counts(normalize=True)

False.    0.8586
True.     0.1414
Name: churned, dtype: float64

In [29]:
df.groupby('churned').mean()

account_length   area_code  intl_plan  voice_mail_plan  \
churned                                                           
False.        99.917074  436.736781   0.063825         0.284416   
True.        102.332390  437.971711   0.281471         0.144272   

         number_vmail_messages  total_day_minutes  total_day_calls  \
churned                                                              
False.                8.291870         175.746564        99.899604   
True.                 4.496464         207.870580       100.817539   

         total_day_charge  total_eve_minutes  total_eve_calls  \
churned                                                         
False.          29.877494         198.805031       100.241556   
True.           35.338416         211.757850        99.884017   

         total_eve_charge  total_night_minutes  total_night_calls  \
churned                                                             
False.          16.898654           199.455113          99.975775   
True.           17.999562           206.078218          99.575672   

         total_night_charge  total_intl_minutes  total_intl_calls  \
churned                                                             
False.             8.975593           10.190869          4.481947   
True.              9.273607           10.692362          4.151344   

         total_intl_charge  number_customer_service_calls  
churned                                                    
False.            2.752055                       1.457722  
True.             2.887426                       2.254597

In [30]:
from scipy.stats import ks_2samp
def run_KS_test(feature):
    dist1 = df.loc[df.churned == 'False.',feature]
    dist2 = df.loc[df.churned == 'True.',feature]
    print(feature+':')
    print(ks_2samp(dist1,dist2),'\n')

In [31]:
from statsmodels.stats.proportion import proportions_ztest
def run_proportion_Z_test(feature):
    dist1 = df.loc[df.churned == 'False.', feature]
    dist2 = df.loc[df.churned == 'True.', feature]
    n1 = len(dist1)
    p1 = dist1.sum()
    n2 = len(dist2)
    p2 = dist2.sum()
    z_score, p_value = proportions_ztest([p1, p2], [n1, n2])
    print(feature+':')
    print('z-score = {}; p-value = {}'.format(z_score, p_value),'\n')

In [32]:
from scipy.stats import chi2_contingency
def run_chi2_test(df, feature):

    dist1 = df.loc[df.churned == 'False.',feature].value_counts().sort_index().tolist()
    dist2 = df.loc[df.churned == 'True.',feature].value_counts().sort_index().tolist()
    chi2, p, dof, expctd = chi2_contingency([dist1,dist2])
    print(feature+':')
    print("chi-square test statistic:", chi2)
    print("p-value", p, '\n')

In [33]:
ks_list = ['account_length','number_vmail_messages','total_day_minutes','total_day_calls','total_day_charge', 'total_eve_minutes', 'total_eve_calls', 'total_eve_charge', 'total_night_minutes', 'total_night_calls', 'total_night_charge', 'total_intl_minutes', 'total_intl_calls', 'total_intl_charge', 'number_customer_service_calls']

In [34]:
z_list = ['voice_mail_plan','intl_plan' ]

In [35]:
for ks_element in ks_list:
    run_KS_test(ks_element)
for z_element in z_list:
    run_proportion_Z_test(z_element)

account_length:
Ks_2sampResult(statistic=0.041589364087651653, pvalue=0.22738382347527208) 

number_vmail_messages:
Ks_2sampResult(statistic=0.13991198460966192, pvalue=9.543970926407943e-11) 

total_day_minutes:
Ks_2sampResult(statistic=0.3045380608740718, pvalue=2.5185677370769294e-49) 

total_day_calls:
Ks_2sampResult(statistic=0.0374314160975846, pvalue=0.35289636482758535) 

total_day_charge:
Ks_2sampResult(statistic=0.3045380608740718, pvalue=2.5185677370769294e-49) 

total_eve_minutes:
Ks_2sampResult(statistic=0.11320491138661636, pvalue=3.499539898662391e-07) 

total_eve_calls:
Ks_2sampResult(statistic=0.02443964072957161, pvalue=0.851266383906971) 

total_eve_charge:
Ks_2sampResult(statistic=0.11320491138661636, pvalue=3.499539898662391e-07) 

total_night_minutes:
Ks_2sampResult(statistic=0.06274383053759104, pvalue=0.01680040720248898) 

total_night_calls:
Ks_2sampResult(statistic=0.0302110175078604, pvalue=0.624008779820064) 

total_night_charge:
Ks_2sampResult(statistic=0.0

In [36]:
ks_list = ['account_length','number_vmail_messages','total_day_minutes','total_day_calls','total_day_charge', 'total_eve_minutes', 'total_eve_calls', 'total_eve_charge', 'total_night_minutes', 'total_night_calls', 'total_night_charge', 'total_intl_minutes', 'total_intl_calls', 'total_intl_charge', 'number_customer_service_calls']

In [37]:
df.churned = df.churned.map({'False.':0, 'True.':1})

In [38]:
corr = df.drop(['area_code'], axis=1).corr()
#corr

In [39]:
# Drop some useless columns
drop_list = ['state', 'account_length', 'total_day_calls', 'total_eve_calls', 'total_night_calls','total_day_minutes', 'total_eve_minutes','total_night_minutes','voice_mail_plan', 'area_code','phone_number','total_intl_minutes', 'total_intl_calls','churned']

In [40]:
X = df.drop(drop_list, axis=1)
y = df.churned.values

In [41]:
# Train/Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
a1_train=X_train.values
a1_test=X_test.values

In [43]:
list_min_max=[]
for i in range(7):
    list_min_max.append([min(a1_train[:,i]),max(a1_train[:,i])])
    print(i,min(a1_train[:,i]),max(a1_train[:,i]))

0 0.0 1.0
1 0.0 52.0
2 0.44 59.76
3 1.9 30.75
4 1.97 17.77
5 0.0 5.4
6 0.0 9.0


In [44]:
for i in range(7):
    a1_train[:,i]=(a1_train[:,i]-list_min_max[i][0])/(list_min_max[i][1]-list_min_max[i][0])

In [45]:
for i in range(7):
    a1_test[:,i]=(a1_test[:,i]-list_min_max[i][0])/(list_min_max[i][1]-list_min_max[i][0])

In [46]:
# Scale the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = pd.DataFrame(scaler.fit_transform(X_train.values), columns=X.columns)
X_test = pd.DataFrame(scaler.transform(X_test.values), columns=X.columns)

print("Feature space holds %d observations and %d features" % X_train.shape)
print("Unique target labels:", np.unique(y_train))

Feature space holds 4000 observations and 7 features
Unique target labels: [0 1]


In [47]:
from keras.models import model_from_json
# load json and create model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")

Using TensorFlow backend.


Loaded model from disk


In [ ]:
print("we have 4 plans of price 200,400,600,800 0fwhich we will give 100 message,80 call minutes and so on")
a=int(input("enter the plan between 1,2,3,4"))
p=int(input( '1st'))
q=int(input('2nd'))
r=int(input('3'))
s=int(input('4'))
t=float(input('5'))
u=int(input('6'))
v=int(input('7'))

Xnew = np.array([[p,q,r,s,t,u,v]])
for i in range(7):
    Xnew[:,i]=(Xnew[:,i]-list_min_max[i][0])/(list_min_max[i][1]-list_min_max[i][0])
#Make a Prediction
ynew =  loaded_model.predict(Xnew)

#Show the inputs and predicted outputs
print("the parameters are=%s and pridicted probality of churning will be=%s" % (Xnew,1-ynew))


we have 4 plans of price 200,400,600,800 0fwhich we will give 100 message,80 call minutes and so on


In [39]:
Xnew

array([[23.        ,  0.23076923,  0.53202967,  1.49393414,  1.33101266,
         2.22222222,  2.55555556]])

In [40]:
p=Xnew
p

array([[23.        ,  0.23076923,  0.53202967,  1.49393414,  1.33101266,
         2.22222222,  2.55555556]])

In [41]:
p

array([[23.        ,  0.23076923,  0.53202967,  1.49393414,  1.33101266,
         2.22222222,  2.55555556]])

In [42]:
list_min_max

[[0.0, 1.0],
 [0.0, 52.0],
 [0.44, 59.76],
 [1.9, 30.75],
 [1.97, 17.77],
 [0.0, 5.4],
 [0.0, 9.0]]

In [43]:
list_min_max[0][0]

0.0

In [44]:
type(list_min_max[0][0])

numpy.float64

In [45]:
Xnew[0][0]

23.0

In [46]:
type(Xnew[0][0])

numpy.float64

In [47]:
Xnew[0][0]-list_min_max[0][0]

23.0

In [48]:
p

array([[23.        ,  0.23076923,  0.53202967,  1.49393414,  1.33101266,
         2.22222222,  2.55555556]])

In [49]:
list_min_max[i][1]-list_min_max[i][0]

9.0

In [50]:
if (a==1):
    message=100+100*ynew
    call=80+80*ynew
    discount=200-200*ynew
elif(a==2):
    message=200+200*ynew
    call=160+100*ynew
    discount=400-400*ynew
elif(a==3):
    message=300+300*ynew
    call=240+100*ynew
    discount=600-600*ynew
elif(a==4):
    message=400+400*ynew
    call=350+350*ynew
    discount=800-800*ynew

In [51]:
message,call,discount

(array([[147.57523]], dtype=float32),
 array([[118.06018]], dtype=float32),
 array([[104.849556]], dtype=float32))

In [52]:
a="5"

In [53]:
print(type(a))

<class 'str'>
